{% set name = "lat_lon_parser" %}
{% set version = "1.3.1" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 62b8191e72150a7bf5d55fe6a8dddf3e20dd4937a995130f74832cd7ede39e91

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - lat_lon_parser
  requires:
    - pytest
  commands:
    - pytest --pyargs lat_lon_parser

about:
  home: https://github.com/NOAA-ORR-ERD/lat_lon_parser
  license: CC0-1.0
  license_file: LICENSE
  summary: parsing latitude-longitude strings
  description: |
    Code for parsing lat-long coordinates in "various" formats,
    and for converting between lat-long formats (e.g. decimal
    degrees to degrees-minutes-seconds). It can also format
    latitude-longitude strings with proper unicode symbols.
  dev_url: https://github.com/NOAA-ORR-ERD/lat_lon_parser

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
